language: python
python: 
  - 3.7.5
env:
  - SECRET_KEY = 'TEST'
services:
  - postgresql
install:
  - pipenv install
  - pip install psycopg
script: 
  - python executivetable_restserver/manage.py test
